[ { id: 1,
    creator_user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    person_id: 
     { name: 'Brett Favre',
       email: [Object],
       phone: [Object],
       value: 1 },
    org_id: null,
    stage_id: 2,
    title: 'Brett Favre deal',
    value: 0,
    currency: 'USD',
    add_time: '2016-04-08 19:07:45',
    update_time: '2016-04-18 22:49:57',
    stage_change_time: null,
    active: true,
    deleted: false,
    status: 'open',
    next_activity_date: null,
    next_activity_time: null,
    next_activity_id: null,
    last_activity_id: null,
    last_activity_date: null,
    lost_reason: null,
    visible_to: '3',
    close_time: null,
    pipeline_id: 1,
    won_time: null,
    lost_time: null,
    products_count: null,
    files_count: null,
    notes_count: 0,
    followers_count: 1,
    email_messages_count: null,
    activities_count: 0,
    done_activities_count: 0,
    undone_activities_count: 0,
    reference_activities_count: 0,
    participants_count: 1,
    expected_close_date: null,
    stage_order_nr: 2,
    person_name: 'Brett Favre',
    org_name: null,
    next_activity_subject: null,
    next_activity_type: null,
    next_activity_duration: null,
    next_activity_note: null,
    formatted_value: '$0',
    rotten_time: null,
    weighted_value: 0,
    formatted_weighted_value: '$0',
    owner_name: 'Joe BO$$',
    cc_email: 'business2+deal1@pipedrivemail.com',
    org_hidden: false,
    person_hidden: false },
  { id: 2,
    creator_user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    person_id: { name: 'John Elway', email: [Object], phone: [Object], value: 2 },
    org_id: null,
    stage_id: 2,
    title: 'John Elway deal',
    value: 0,
    currency: 'USD',
    add_time: '2016-04-08 19:07:53',
    update_time: '2016-04-18 22:49:57',
    stage_change_time: '2016-04-08 19:07:56',
    active: true,
    deleted: false,
    status: 'open',
    next_activity_date: null,
    next_activity_time: null,
    next_activity_id: null,
    last_activity_id: null,
    last_activity_date: null,
    lost_reason: null,
    visible_to: '3',
    close_time: null,
    pipeline_id: 1,
    won_time: null,
    lost_time: null,
    products_count: null,
    files_count: null,
    notes_count: 0,
    followers_count: 1,
    email_messages_count: null,
    activities_count: 0,
    done_activities_count: 0,
    undone_activities_count: 0,
    reference_activities_count: 0,
    participants_count: 1,
    expected_close_date: null,
    stage_order_nr: 2,
    person_name: 'John Elway',
    org_name: null,
    next_activity_subject: null,
    next_activity_type: null,
    next_activity_duration: null,
    next_activity_note: null,
    formatted_value: '$0',
    rotten_time: null,
    weighted_value: 0,
    formatted_weighted_value: '$0',
    owner_name: 'Joe BO$$',
    cc_email: 'business2+deal2@pipedrivemail.com',
    org_hidden: false,
    person_hidden: false },
  { id: 3,
    creator_user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    person_id: 
     { name: 'Joe Montana',
       email: [Object],
       phone: [Object],
       value: 3 },
    org_id: null,
    stage_id: 2,
    title: 'Joe Montana deal',
    value: 0,
    currency: 'USD',
    add_time: '2016-04-08 19:08:05',
    update_time: '2016-04-18 22:49:57',
    stage_change_time: null,
    active: true,
    deleted: false,
    status: 'open',
    next_activity_date: null,
    next_activity_time: null,
    next_activity_id: null,
    last_activity_id: null,
    last_activity_date: null,
    lost_reason: null,
    visible_to: '3',
    close_time: null,
    pipeline_id: 1,
    won_time: null,
    lost_time: null,
    products_count: null,
    files_count: null,
    notes_count: 0,
    followers_count: 1,
    email_messages_count: null,
    activities_count: 0,
    done_activities_count: 0,
    undone_activities_count: 0,
    reference_activities_count: 0,
    participants_count: 1,
    expected_close_date: null,
    stage_order_nr: 2,
    person_name: 'Joe Montana',
    org_name: null,
    next_activity_subject: null,
    next_activity_type: null,
    next_activity_duration: null,
    next_activity_note: null,
    formatted_value: '$0',
    rotten_time: null,
    weighted_value: 0,
    formatted_weighted_value: '$0',
    owner_name: 'Joe BO$$',
    cc_email: 'business2+deal3@pipedrivemail.com',
    org_hidden: false,
    person_hidden: false },
  { id: 4,
    creator_user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    person_id: { name: 'Dan Marino', email: [Object], phone: [Object], value: 4 },
    org_id: null,
    stage_id: 2,
    title: 'Dan Marino deal',
    value: 0,
    currency: 'USD',
    add_time: '2016-04-08 19:08:16',
    update_time: '2016-04-18 22:49:57',
    stage_change_time: null,
    active: true,
    deleted: false,
    status: 'open',
    next_activity_date: null,
    next_activity_time: null,
    next_activity_id: null,
    last_activity_id: null,
    last_activity_date: null,
    lost_reason: null,
    visible_to: '3',
    close_time: null,
    pipeline_id: 1,
    won_time: null,
    lost_time: null,
    products_count: null,
    files_count: null,
    notes_count: 0,
    followers_count: 1,
    email_messages_count: null,
    activities_count: 0,
    done_activities_count: 0,
    undone_activities_count: 0,
    reference_activities_count: 0,
    participants_count: 1,
    expected_close_date: null,
    stage_order_nr: 2,
    person_name: 'Dan Marino',
    org_name: null,
    next_activity_subject: null,
    next_activity_type: null,
    next_activity_duration: null,
    next_activity_note: null,
    formatted_value: '$0',
    rotten_time: null,
    weighted_value: 0,
    formatted_weighted_value: '$0',
    owner_name: 'Joe BO$$',
    cc_email: 'business2+deal4@pipedrivemail.com',
    org_hidden: false,
    person_hidden: false },
  { id: 5,
    creator_user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    person_id: 
     { name: 'Warren Moon',
       email: [Object],
       phone: [Object],
       value: 5 },
    org_id: null,
    stage_id: 2,
    title: 'Warren Moon deal',
    value: 0,
    currency: 'USD',
    add_time: '2016-04-08 19:08:38',
    update_time: '2016-04-18 22:49:57',
    stage_change_time: '2016-04-08 19:08:40',
    active: true,
    deleted: false,
    status: 'open',
    next_activity_date: null,
    next_activity_time: null,
    next_activity_id: null,
    last_activity_id: null,
    last_activity_date: null,
    lost_reason: null,
    visible_to: '3',
    close_time: null,
    pipeline_id: 1,
    won_time: null,
    lost_time: null,
    products_count: null,
    files_count: null,
    notes_count: 0,
    followers_count: 1,
    email_messages_count: null,
    activities_count: 0,
    done_activities_count: 0,
    undone_activities_count: 0,
    reference_activities_count: 0,
    participants_count: 1,
    expected_close_date: null,
    stage_order_nr: 2,
    person_name: 'Warren Moon',
    org_name: null,
    next_activity_subject: null,
    next_activity_type: null,
    next_activity_duration: null,
    next_activity_note: null,
    formatted_value: '$0',
    rotten_time: null,
    weighted_value: 0,
    formatted_weighted_value: '$0',
    owner_name: 'Joe BO$$',
    cc_email: 'business2+deal5@pipedrivemail.com',
    org_hidden: false,
    person_hidden: false },
  { id: 6,
    creator_user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    person_id: { name: 'Jim Kelly', email: [Object], phone: [Object], value: 6 },
    org_id: null,
    stage_id: 2,
    title: 'Jim Kelly deal',
    value: 0,
    currency: 'USD',
    add_time: '2016-04-08 19:09:05',
    update_time: '2016-04-18 22:49:58',
    stage_change_time: '2016-04-08 19:09:08',
    active: true,
    deleted: false,
    status: 'open',
    next_activity_date: null,
    next_activity_time: null,
    next_activity_id: null,
    last_activity_id: null,
    last_activity_date: null,
    lost_reason: null,
    visible_to: '3',
    close_time: null,
    pipeline_id: 1,
    won_time: null,
    lost_time: null,
    products_count: null,
    files_count: null,
    notes_count: 0,
    followers_count: 1,
    email_messages_count: null,
    activities_count: 0,
    done_activities_count: 0,
    undone_activities_count: 0,
    reference_activities_count: 0,
    participants_count: 1,
    expected_close_date: null,
    stage_order_nr: 2,
    person_name: 'Jim Kelly',
    org_name: null,
    next_activity_subject: null,
    next_activity_type: null,
    next_activity_duration: null,
    next_activity_note: null,
    formatted_value: '$0',
    rotten_time: null,
    weighted_value: 0,
    formatted_weighted_value: '$0',
    owner_name: 'Joe BO$$',
    cc_email: 'business2+deal6@pipedrivemail.com',
    org_hidden: false,
    person_hidden: false },
  { id: 9,
    creator_user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    user_id: 
     { id: 1236582,
       name: 'Joe BO$$',
       email: 'joeboss12345678@gmail.com',
       has_pic: true,
       pic_hash: '59ad0fe12f884822c205e89f78235503',
       active_flag: true,
       value: 1236582 },
    person_id: 
     { name: 'Stagetest Anderson',
       email: [Object],
       phone: [Object],
       value: 9 },
    org_id: null,
    stage_id: 2,
    title: 'Stagetest Anderson deal',
    value: 0,
    currency: 'USD',
    add_time: '2016-04-14 16:48:13',
    update_time: '2016-04-18 22:49:57',
    stage_change_time: '2016-04-14 16:49:37',
    active: true,
    deleted: false,
    status: 'open',
    next_activity_date: null,
    next_activity_time: null,
    next_activity_id: null,
    last_activity_id: null,
    last_activity_date: null,
    lost_reason: null,
    visible_to: '3',
    close_time: null,
    pipeline_id: 1,
    won_time: null,
    lost_time: null,
    products_count: null,
    files_count: null,
    notes_count: 0,
    followers_count: 1,
    email_messages_count: null,
    activities_count: 0,
    done_activities_count: 0,
    undone_activities_count: 0,
    reference_activities_count: 0,
    participants_count: 1,
    expected_close_date: null,
    stage_order_nr: 2,
    person_name: 'Stagetest Anderson',
    org_name: null,
    next_activity_subject: null,
    next_activity_type: null,
    next_activity_duration: null,
    next_activity_note: null,
    formatted_value: '$0',
    rotten_time: null,
    weighted_value: 0,
    formatted_weighted_value: '$0',
    owner_name: 'Joe BO$$',
    cc_email: 'business2+deal9@pipedrivemail.com',
    org_hidden: false,
    person_hidden: false }]

